### PR TITLE
Open up the support for Python>=3.9 to align with Kedro 0.19

### PR DESCRIPTION
**Pull request by noklam**
Is there a specific reason why this only support Python 3.11+? It looks like it can support 3.9+ that aligns with Kedro 0.19+

### CODE REVIEW

**Comment by JenspederM** [comment]
I've had some issues getting the test suite up and running on github with lower versions.. You're welcome to give it a go :)

**Comment by noklam** [comment]
@JenspederM Why do you pin `ipython` to 8.26.0? 

https://pypi.org/project/ipython/, this is the latest version and thus doens't exist in older version. Is it possible to set a lower bound or remove it altogether?

**Comment by noklam** [comment]
I am not familar with `rye`, but seems that during the installation step it force the installation follow either `requirements.txt` or `requirements-dev.lock`? These requirements are too restricted as a library, it should only be pinned on the application side.

**Comment by JenspederM** [comment]
I have been a bit lazy with the type system, so I didn't support <3.11.

I have made the necessary changes in #29 🙂

**Pull request closed without merging**
