### PR TITLE
feat(env): add --env parameter to the python_wheel_task parameters

### PR DESCRIPTION
**Pull request by npfp**

### CODE REVIEW

**Comment by JenspederM** [comment]
Awesome! Let's see with the tests.

**Comment by JenspederM** [comment]
I just have to update the token. I'll do that tonight or tomorrow and rerun tests. 

Thank you for making this PR!

**Comment by npfp** [comment]
You're very welcome! Thx for the plugin, it's very useful for us.

**Comment by JenspederM** [comment]
@npfp Hello again, 

I had made a mistake when setting up the test workflow, which prohibited use of secrets and ultimately meant that tests couldn't run. I believe that I have fixed this now. However, for the changes to be applied to your PRs you will have to incorporate the changes from main into your PRs. 

I'm sorry for the inconvenience!

**Review by JenspederM — DISMISSED** [review]
LGTM

**Comment by JenspederM** [comment]
@npfp Just need a signed commit, then this is good to go ;)

**Comment by npfp** [comment]
Sorry I completely messed up with my rebase. :-( 

Let me fix this...

**Comment by npfp** [comment]
That should be good now.

**Comment by JenspederM** [comment]
> That should be good now.

Unfortunately, it's still not signed properly

**Comment by npfp** [comment]
@JenspederM I'm not ure how to interpret this:

Screenshot 2024-08-25 at 14 22 02

It looks to me it's fine on this branch (2 commits are signed). Could it be there're unsigned commits in `main` that would trigger this rule?

**Comment by JenspederM** [comment]
Your commits are now signed-off, but not "signed", i.e., they are missing their `verified` emblem
image

**Comment by JenspederM** [comment]
> @JenspederM I'm not ure how to interpret this:
> 
> 
> 
> Screenshot 2024-08-25 at 14 22 02
> 
> 
> 
> It looks to me it's fine on this branch (2 commits are signed). Could it be there're unsigned commits in `main` that would trigger this rule?
> 
> 
> 
> 

You were right. I was working on a misconfigured system, so when I did the pipeline changes I introduced some unverified commits to main which broke the system. 

Can I get you to reset both your prs against the current main?

**Review by JenspederM — APPROVED** [review]

**Comment by JenspederM** [comment]
Your commits are still not verified. 

You can set it up using this guide: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Pull request merged**
